---
- hosts: localhost
  
  vars: 
    - githubuser: "{{ lookup('env', 'githubuser') }}"
    - githubpassword: "{{ lookup('env', 'githubpassword') }}"
  
  roles:
    - dependencies
    - repo&modules
    - provisionserver